services:
    sonata.admin.news:
        class: Site\NewsBundle\Admin\NewsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "News" }
        arguments:
            - ~
            - Site\NewsBundle\Entity\News
            - ~
        calls:
            - [ setTranslationDomain, [SiteNewsBundle]]
            
    sonata.admin.tags:
        class: Site\NewsBundle\Admin\TagsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Tags" }
        arguments:
            - ~
            - Site\NewsBundle\Entity\Tag
            - ~
        calls:
            - [ setTranslationDomain, [SiteNewsBundle]]        

    sonata.admin.categories:
        class: Site\NewsBundle\Admin\CategoriesAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Categories" }
        arguments:
            - ~
            - Site\NewsBundle\Entity\Category
            - ~
        calls:
            - [ setTranslationDomain, [SiteNewsBundle]]        